[general]
import = [
	"./iterm.toml"
]

[font]
size = 12.0

[font.normal]
family = "Hack"
style = "Regular"

[window]
opacity = 0.9
dynamic_padding = true
#[colors.primary]
#background = "#000000"
#foreground = "#FFFFFF"

[window.padding]
x = 8
y = 3

