# Fixing colors
set-option -sa terminal-overrides ",xterm*:Tc"

# Setting the mouse on
set -g mouse on

# Rebind split keys
bind % split-window -c "#{pane_current_path}"
bind '"' split-window -h -c "#{pane_current_path}"

# Start with 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Move bar to top
# set-option -g status-position top
